import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { verifyLinkToken } from "@/lib/customer-link";
import { sendMembershipDetails } from "@/lib/notifications";

// POST /api/liff/link
// Links a LINE account to an existing customer record. Two ways to identify the
// customer:
//   • token — a signed per-customer link generated by staff (one-tap, no typing)
//   • phone — the customer types the phone registered with the shop (fallback)
// After a successful link, the customer's membership card is pushed to LINE.
export async function POST(request: Request) {
  const { lineUserId, phone, token, displayName, pictureUrl } = await request.json();

  if (!lineUserId) {
    return NextResponse.json({ error: "lineUserId is required" }, { status: 400 });
  }

  // Resolve the target customer from token (preferred) or phone.
  let target: { id: string; name: string; nickname: string | null } | null = null;
  if (token) {
    const customerId = verifyLinkToken(token);
    if (!customerId) {
      return NextResponse.json({ error: "ลิงก์หมดอายุหรือไม่ถูกต้อง กรุณาขอลิงก์ใหม่จากพนักงาน" }, { status: 400 });
    }
    target = await prisma.customer.findUnique({
      where:  { id: customerId },
      select: { id: true, name: true, nickname: true },
    });
    if (!target) return NextResponse.json({ error: "ไม่พบข้อมูลลูกค้า" }, { status: 404 });
  } else if (phone) {
    const normalised = phone.trim().replace(/\s/g, "").replace(/^\+66/, "0");
    target = await prisma.customer.findUnique({
      where:  { phone: normalised },
      select: { id: true, name: true, nickname: true },
    });
    if (!target) return NextResponse.json({ error: "ไม่พบเบอร์โทรนี้ในระบบ กรุณาติดต่อพนักงาน" }, { status: 404 });
  } else {
    return NextResponse.json({ error: "token or phone is required" }, { status: 400 });
  }

  // Is this LINE account already linked to a customer?
  const alreadyLinked = await prisma.customer.findUnique({ where: { lineUserId } });
  if (alreadyLinked) {
    if (alreadyLinked.id === target.id) {
      // Linked to the right record already — still (re)send the membership card.
      sendMembershipDetails(target.id).catch(e => console.error("[notify] membership details failed", e));
      return NextResponse.json({ ok: true, already: true, name: alreadyLinked.nickname || alreadyLinked.name });
    }
    // Linked to a *different* record — don't hijack it; let staff sort it out.
    return NextResponse.json(
      { error: "บัญชี LINE นี้เชื่อมต่อกับลูกค้าอื่นแล้ว กรุณาติดต่อพนักงาน" },
      { status: 409 },
    );
  }

  // Link the LINE account to the target customer.
  await prisma.customer.update({
    where: { id: target.id },
    data: {
      lineUserId,
      ...(pictureUrl ? { pictureUrl } : {}),
      // Sync display name only if the stored name is a placeholder
      ...(displayName && target.name === "Walk-in" ? { name: displayName } : {}),
    },
  });

  // Auto-send the membership card (no-op if they have no active membership).
  sendMembershipDetails(target.id).catch(e => console.error("[notify] membership details failed", e));

  return NextResponse.json({ ok: true, already: false, name: target.nickname || target.name });
}
